# Generated by Django 5.2.1 on 2025-06-28 16:26

import Trave_Packages_Management.models
import autoslug.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setting', '0012_ourgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='package_name', unique=True)),
                ('destination', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('no_person', models.IntegerField(help_text='No Person for the package include chldren')),
                ('description', tinymce.models.HTMLField(help_text='Enter the description of the travel package')),
                ('thumbnail_image', models.FileField(blank=True, null=True, upload_to=Trave_Packages_Management.models.package_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_package', to='setting.categories')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_package', to='setting.countries')),
            ],
            options={
                'verbose_name_plural': 'Our Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
