# Generated by Django 5.2.3 on 2025-07-18 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trave_Packages_Management', '0004_alter_travelpackage_hotel_type_travelenquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='travelenquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_enquiry', to=settings.AUTH_USER_MODEL),
        ),
    ]
