# Generated by Django 5.2.3 on 2025-07-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxAndGateway', '0002_taxsetting_tax_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsetting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
