# Generated by Django 4.2.24 on 2025-12-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payment_settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="taxinfo",
            options={
                "verbose_name": "Tax Information",
                "verbose_name_plural": "Tax Informations",
            },
        ),
    ]
