# Generated by Django 4.2.24 on 2025-12-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_settings", "0002_alter_taxinfo_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taxinfo",
            old_name="text_apply_type",
            new_name="tex_apply_type",
        ),
        migrations.AddField(
            model_name="taxinfo",
            name="tax_title",
            field=models.CharField(default="Default Tax Title", max_length=100),
        ),
    ]
