# Generated by Django 4.2.24 on 2025-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payment_settings",
            "0003_rename_text_apply_type_taxinfo_tex_apply_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxinfo",
            name="tax_title",
            field=models.CharField(default=True, max_length=100),
        ),
    ]
