# Generated by Django 4.2.24 on 2025-12-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_settings", "0004_alter_taxinfo_tax_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxinfo",
            name="tax_title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
