# Generated by Django 4.2.24 on 2025-12-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_settings", "0005_alter_taxinfo_tax_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="RazorpaySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway_mode",
                    models.CharField(
                        choices=[("Test", "Test"), ("Live", "Live")],
                        default="Test",
                        max_length=50,
                    ),
                ),
                ("key_id", models.CharField(blank=True, max_length=100, null=True)),
                ("key_secret", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Razorpay Setting",
                "verbose_name_plural": "Razorpay Settings",
            },
        ),
    ]
