# Generated by Django 4.2.24 on 2025-12-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_settings", "0006_razorpaysettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Booking_id", models.CharField(max_length=200, unique=True)),
                ("payment_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone_no", models.CharField(max_length=15)),
                ("user_email", models.EmailField(max_length=254)),
                (
                    "sub_total_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "tax_info",
                    models.TextField(blank=True, null=True, verbose_name="Tax Info"),
                ),
                ("package_title", models.CharField(max_length=200)),
                ("package_description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("no_person", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
    ]
