# Generated by Django 4.2.24 on 2025-12-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_settings", "0007_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
