# Generated by Django 4.2.24 on 2025-11-18 16:56

from django.db import migrations, models
import park_facilities.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ParkFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    tinymce.models.HTMLField(verbose_name="Slider Description"),
                ),
                (
                    "image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=park_facilities.models.facility_image_upload_path,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        choices=[(True, "Active"), (False, "Deactive")], default=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
