# Generated by Django 4.2.24 on 2025-11-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park_facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parkfacility",
            options={
                "ordering": ["title"],
                "verbose_name": "Facility List",
                "verbose_name_plural": "Facility List",
            },
        ),
    ]
