# Generated by Django 4.2.24 on 2025-11-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_facilities", "0002_alter_parkfacility_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkfacility",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
