# Generated by Django 4.2.24 on 2025-11-18 17:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("park_facilities", "0003_alter_parkfacility_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("service_icon", models.CharField(max_length=100)),
                (
                    "description",
                    tinymce.models.HTMLField(verbose_name="Service Description"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service List",
                "verbose_name_plural": "Services List",
                "ordering": ["title"],
            },
        ),
    ]
