# Generated by Django 4.2.24 on 2025-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_facilities", "0004_parkservice"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkTimings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=150)),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Park Timing",
                "verbose_name_plural": "Park Timings",
                "ordering": ["id"],
            },
        ),
    ]
