# Generated by Django 4.2.24 on 2025-11-19 15:55

from django.db import migrations, models
import park_facilities.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("park_facilities", "0005_parktimings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParAttractions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "description",
                    tinymce.models.HTMLField(verbose_name="Attractions Description"),
                ),
                (
                    "image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=park_facilities.models.attractions_image_upload_path,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Park Attractions",
                "verbose_name_plural": "Park Attractions",
                "ordering": ["title"],
            },
        ),
        migrations.AlterField(
            model_name="parkfacility",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Facility Description"),
        ),
    ]
