# Generated by Django 4.2.24 on 2025-11-25 18:10

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park_facilities", "0006_parattractions_alter_parkfacility_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkfacility",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
    ]
