# Generated by Django 5.1.1 on 2025-03-20 17:56

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='category_name', unique=True)),
            ],
        ),
    ]
