# Generated by Django 5.1.1 on 2025-03-24 17:11

import autoslug.fields
import django.db.models.deletion
import product.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256)),
                ('product_price', models.IntegerField(max_length=100)),
                ('product_discription', tinymce.models.HTMLField()),
                ('product_image', models.FileField(default=None, max_length=255, null=True, upload_to=product.models.user_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='product_name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
