# Generated by Django 5.1.1 on 2025-03-24 17:12

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(default=None, max_length=256, null=True, upload_to=product.models.user_image_upload_path),
        ),
    ]
