# Generated by Django 5.1.1 on 2025-04-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productdelivery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category List'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product List'},
        ),
        migrations.AlterModelOptions(
            name='productdelivery',
            options={'verbose_name': 'Product Delivery', 'verbose_name_plural': 'Product Deliveries'},
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
    ]
