# Generated by Django 5.1.1 on 2025-04-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_productdelivery_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='product_price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='total_price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
