# Generated by Django 5.1.1 on 2025-04-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productdelivery_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_apply_type', models.CharField(choices=[('Flat', 'Flat'), ('Percentage', 'Percentage')], default='Percentage', max_length=50)),
                ('tax_value', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tax Setting',
                'verbose_name_plural': 'Tax Setting',
            },
        ),
    ]
