# Generated by Django 5.1.1 on 2025-04-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_shippingcostsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcostsetting',
            name='cost_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
