# Generated by Django 5.1.1 on 2025-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_shippingcostsetting_cost_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='shipping_cost',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='shipping_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='tax_apply',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='productdelivery',
            name='tax_apply_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
