# Generated by Django 5.1.1 on 2025-04-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productdelivery_shipping_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='tax_value',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
