# Generated by Django 5.1.1 on 2025-04-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productdelivery_tax_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='order_id',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
