# Generated by Django 5.1.1 on 2025-04-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productdelivery_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Razorpay', 'Razorpay')], default='Razorpay', max_length=50),
        ),
    ]
