# Generated by Django 5.1.1 on 2025-04-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productdelivery_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdelivery',
            old_name='product',
            new_name='product_id',
        ),
    ]
