# Generated by Django 5.1.1 on 2025-04-23 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_product_productdelivery_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdelivery',
            old_name='product_id',
            new_name='product',
        ),
    ]
