# Generated by Django 5.1.1 on 2025-04-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_product_id_productdelivery_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpaySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_mode', models.CharField(choices=[('Test', 'Test'), ('Live', 'Live')], default='Test', max_length=50)),
                ('razorpay_key_id', models.CharField(max_length=250)),
                ('razorpay_secret_key', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Razorpay Setting',
            },
        ),
    ]
