# Generated by Django 5.2.3 on 2025-07-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaxAndGateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxsetting',
            name='tax_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
