# Generated by Django 5.2.3 on 2025-08-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaxAndGateway', '0004_razorpaysetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='razorpaysetting',
            options={'verbose_name_plural': 'Razorpay Gateway Setting'},
        ),
    ]
