# Generated by Django 4.2.24 on 2025-12-03 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_blogcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="blogCategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blogs.blogcategory",
            ),
        ),
    ]
