# Generated by Django 5.2.1 on 2025-06-01 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='Site Name')),
                ('site_keywords', models.CharField(max_length=255, verbose_name='Site Keywords')),
                ('site_email', models.EmailField(max_length=254, verbose_name='Site Email')),
                ('site_hr_email', models.EmailField(max_length=254, verbose_name='Hr Email')),
                ('site_phone', models.CharField(max_length=20, verbose_name='Site Phone')),
                ('site_fax', models.CharField(max_length=20, verbose_name='Site Phone')),
                ('site_address', models.CharField(max_length=255, verbose_name='Site Address')),
                ('site_contry', models.CharField(max_length=255, verbose_name='Contry')),
                ('site_city', models.CharField(max_length=255, verbose_name='City')),
                ('site_logo', models.CharField(max_length=255, verbose_name='Logo')),
                ('site_description', models.TextField(verbose_name='Site Description')),
            ],
            options={
                'verbose_name': 'Web Setting',
                'verbose_name_plural': 'Web Settings',
                'ordering': ['site_name'],
            },
        ),
    ]
