# Generated by Django 5.2.1 on 2025-06-05 10:26

import autoslug.fields
import setting.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_socialmedialink_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to=setting.models.jobs_upload_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs List',
            },
        ),
    ]
