# Generated by Django 5.2.1 on 2025-06-08 17:39

import django.db.models.deletion
import setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0004_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiveJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to=setting.models.job_applications_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='setting.jobs')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
