# Generated by Django 5.2.1 on 2025-06-08 17:49

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0005_receivejobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivejobapplication',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
