# Generated by Django 5.2.1 on 2025-06-25 11:38

import setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_description', models.TextField()),
                ('category_thumbnail_image', models.FileField(blank=True, null=True, upload_to=setting.models.category_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Category List',
                'ordering': ['-created_at'],
            },
        ),
    ]
