# Generated by Django 5.2.1 on 2025-06-25 12:27

import django.db.models.deletion
import setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail_image', models.FileField(blank=True, null=True, upload_to=setting.models.gallery_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_galleries', to='setting.categories')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_galleries', to='setting.countries')),
            ],
            options={
                'verbose_name_plural': 'Our Gallery',
                'ordering': ['-created_at'],
            },
        ),
    ]
