# Generated by Django 5.2.1 on 2025-06-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trave_Packages_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpackage',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Travel Package List'},
        ),
    ]
