# Generated by Django 5.2.3 on 2025-07-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trave_Packages_Management', '0002_alter_travelpackage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='hotel_type',
            field=models.CharField(choices=[('5_star', '5 Star'), ('4_star', '4 Star'), ('3_star', '3 Star')], default='3_star', max_length=10),
        ),
    ]
