# Generated by Django 5.2.3 on 2025-07-17 10:47

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trave_Packages_Management', '0003_travelpackage_hotel_type'),
        ('setting', '0013_ourgallery_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpackage',
            name='hotel_type',
            field=models.CharField(choices=[('5_star', '5 Star'), ('4_star', '4 Star'), ('3_star', '3 Star'), ('2_star', '2 Star'), ('1_star', '1 Star')], default='3_star', max_length=10),
        ),
        migrations.CreateModel(
            name='TravelEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('no_person', models.IntegerField(help_text='No Person for the enquiry include chldren')),
                ('hotel_type', models.CharField(choices=[('5_star', '5 Star'), ('4_star', '4 Star'), ('3_star', '3 Star'), ('2_star', '2 Star'), ('1_star', '1 Star')], default='3_star', max_length=10)),
                ('tourdetails', tinymce.models.HTMLField(help_text='Enter please send your tour details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_enquiry', to='setting.categories')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_enquiry', to='setting.countries')),
            ],
            options={
                'verbose_name_plural': 'Travel Enquiry',
                'ordering': ['-created_at'],
            },
        ),
    ]
