# Generated by Django 5.2.1 on 2025-06-01 10:19

import setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media_title', models.CharField(max_length=50, verbose_name='Social Media Platform')),
                ('social_media_url', models.CharField(max_length=50, verbose_name='Social Media URL')),
                ('social_media_icon', models.CharField(max_length=50, verbose_name='Social Media icon')),
            ],
            options={
                'verbose_name': 'Social Media Link',
                'verbose_name_plural': 'Social Media Links',
                'ordering': ['social_media_title'],
            },
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'ordering': ['site_name'], 'verbose_name': 'Web Setting', 'verbose_name_plural': 'Website Setting'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_fax',
            field=models.CharField(max_length=20, verbose_name='Site FAX'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='site_logo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to=setting.models.logo_image_upload_path),
        ),
    ]
