# Generated by Django 5.2.1 on 2025-06-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_socialmedialink_alter_setting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedialink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
