# Generated by Django 5.2.1 on 2025-06-24 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0007_aboutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivejobapplication',
            name='job',
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
        migrations.DeleteModel(
            name='ReceiveJobApplication',
        ),
    ]
