# Generated by Django 5.2.1 on 2025-06-25 09:49

import setting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0008_remove_receivejobapplication_job_delete_jobs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=150)),
                ('slider_sub_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('slider_button_title', models.CharField(max_length=150)),
                ('slider_button_url', models.CharField(max_length=255)),
                ('slider_image', models.FileField(blank=True, null=True, upload_to=setting.models.slider_image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Slider Setting',
                'ordering': ['-created_at'],
            },
        ),
    ]
