# Generated by Django 5.2.1 on 2025-06-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0009_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Country List',
                'ordering': ['-created_at'],
            },
        ),
    ]
