# Generated by Django 5.1.1 on 2025-03-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=120)),
                ('site_email', models.EmailField(max_length=254)),
                ('site_phone_no', models.CharField(max_length=15)),
                ('site_address', models.TextField()),
                ('facebook_link', models.TextField(blank=True, null=True)),
                ('twitter_link', models.TextField(blank=True, null=True)),
                ('linkedin_link', models.TextField(blank=True, null=True)),
                ('instagram_link', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
