# Generated by Django 5.1.1 on 2025-03-03 16:15

import siteSetting.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to=siteSetting.models.user_image_upload_path)),
            ],
        ),
    ]
