# Generated by Django 5.1.1 on 2025-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0002_aboutusinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
