# Generated by Django 5.1.1 on 2025-03-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0003_subscribelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=120)),
                ('user_message', models.TextField()),
            ],
        ),
    ]
