# Generated by Django 5.1.1 on 2025-04-11 05:17

import siteSetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0004_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_feedback', models.TextField()),
                ('customer_image', models.FileField(default=None, max_length=250, null=True, upload_to=siteSetting.models.testimonial_user_image_upload_path)),
            ],
        ),
    ]
