# Generated by Django 5.1.1 on 2025-04-13 14:12

import siteSetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(max_length=120)),
                ('slide_description', models.TextField()),
                ('slide_image', models.FileField(default=None, max_length=250, null=True, upload_to=siteSetting.models.slider_image_upload_path)),
                ('slide_buttont_ext_1', models.CharField(max_length=120)),
                ('slide_buttont_ext_link_1', models.TextField(blank=True, null=True)),
                ('slide_buttont_ext_2', models.CharField(max_length=120)),
                ('slide_buttont_ext_link_2', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
