# Generated by Django 5.1.1 on 2025-04-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSetting', '0006_sliderlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutusinfo',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name_plural': 'Website Settings'},
        ),
        migrations.AlterModelOptions(
            name='sliderlist',
            options={'verbose_name_plural': 'Slider List'},
        ),
        migrations.AlterModelOptions(
            name='subscribelist',
            options={'verbose_name_plural': 'Subscribe List'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name_plural': 'Testimonial'},
        ),
    ]
