# Generated by Django 5.1.1 on 2025-03-04 05:47

import autoslug.fields
import blogs.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to=blogs.models.user_image_upload_path)),
            ],
        ),
    ]
