# Generated by Django 5.2.3 on 2025-08-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trave_Packages_Management', '0006_quotationinfo'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglist',
            name='TravelEnquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_TravelEnquiry', to='Trave_Packages_Management.travelenquiry'),
        ),
    ]
