# Generated by Django 4.2.24 on 2025-09-16 18:11

from django.db import migrations, models
import website_setting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(max_length=100, verbose_name="Site Name"),
                ),
                (
                    "site_keywords",
                    models.CharField(max_length=255, verbose_name="Site Keywords"),
                ),
                (
                    "site_email",
                    models.EmailField(max_length=254, verbose_name="Site Email"),
                ),
                (
                    "site_hr_email",
                    models.EmailField(max_length=254, verbose_name="Hr Email"),
                ),
                (
                    "site_phone",
                    models.CharField(max_length=20, verbose_name="Site Phone"),
                ),
                ("site_fax", models.CharField(max_length=20, verbose_name="Site FAX")),
                (
                    "site_address",
                    models.CharField(max_length=255, verbose_name="Site Address"),
                ),
                (
                    "site_contry",
                    models.CharField(max_length=255, verbose_name="Contry"),
                ),
                ("site_city", models.CharField(max_length=255, verbose_name="City")),
                (
                    "site_logo",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=website_setting.models.logo_image_upload_path,
                    ),
                ),
                ("site_description", models.TextField(verbose_name="Site Description")),
            ],
            options={
                "verbose_name": "Web Setting",
                "verbose_name_plural": "Website Setting",
                "ordering": ["site_name"],
            },
        ),
    ]
