# Generated by Django 4.2.24 on 2025-11-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "facebook_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Facebook URL"
                    ),
                ),
                (
                    "x_url",
                    models.TextField(blank=True, null=True, verbose_name="X URL"),
                ),
                (
                    "instagram_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                (
                    "linkedIn_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="LinkedIn URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Social Media Link",
                "verbose_name_plural": "Social Media Links",
            },
        ),
    ]
