# Generated by Django 4.2.24 on 2025-11-18 16:21

import autoslug.fields
from django.db import migrations, models
import tinymce.models
import website_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0002_socialmedialinks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Slider Title"),
                ),
                (
                    "sub_title",
                    models.CharField(max_length=200, verbose_name="Slider SubTitle"),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(verbose_name="Slider Description"),
                ),
                (
                    "image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=website_setting.models.slider_image_upload_path,
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False,
                        populate_from="title",
                        unique=True,
                        verbose_name="Slider Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Slider",
                "verbose_name_plural": "Sliders",
                "ordering": ["title"],
            },
        ),
    ]
