# Generated by Django 4.2.24 on 2025-11-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0003_slider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="description",
            field=models.TextField(verbose_name="Slider Description"),
        ),
    ]
