# Generated by Django 4.2.24 on 2025-11-19 16:36

from django.db import migrations, models
import website_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0004_alter_slider_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Client Name")),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="Client Designation"),
                ),
                ("feedback", models.TextField(verbose_name="Client Feedback")),
                (
                    "image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=website_setting.models.user_image_upload_path,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "★ 1 Star"),
                            (2, "★★ 2 Stars"),
                            (3, "★★★ 3 Stars"),
                            (4, "★★★★ 4 Stars"),
                            (5, "★★★★★ 5 Stars"),
                        ],
                        verbose_name="Client Rating",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
                "ordering": ["name"],
            },
        ),
    ]
