# Generated by Django 4.2.24 on 2025-11-19 17:05

from django.db import migrations, models
import website_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0005_testimonial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Member Name")),
                (
                    "designation",
                    models.CharField(max_length=100, verbose_name="Member Designation"),
                ),
                ("bio", models.TextField(verbose_name="Member Bio")),
                (
                    "image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to=website_setting.models.team_image_upload_path,
                    ),
                ),
                (
                    "fb_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Facebook URL"
                    ),
                ),
                (
                    "twitter_url",
                    models.TextField(blank=True, null=True, verbose_name="Twitter URL"),
                ),
                (
                    "linkedin_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="LinkedIn URL"
                    ),
                ),
                (
                    "instagram_url",
                    models.TextField(
                        blank=True, null=True, verbose_name="Instagram URL"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Team Member",
                "verbose_name_plural": "Team Members",
                "ordering": ["name"],
            },
        ),
    ]
