# Generated by Django 4.2.24 on 2025-11-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0006_teammember"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Image Title")),
                (
                    "image",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="gallery_images/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Gallery Image",
                "verbose_name_plural": "Gallery Images",
                "ordering": ["-created_at"],
            },
        ),
    ]
