# Generated by Django 4.2.24 on 2025-11-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website_setting", "0007_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="About Us Heading"),
                ),
                ("description", models.TextField(verbose_name="About Us")),
                (
                    "image",
                    models.FileField(
                        default=None, max_length=250, null=True, upload_to="about_us/"
                    ),
                ),
                (
                    "years_experiance",
                    models.CharField(max_length=255, verbose_name="Years Experiance"),
                ),
                (
                    "happy_visitors",
                    models.CharField(max_length=255, verbose_name="Happy Visitors"),
                ),
                (
                    "awwards_winning",
                    models.CharField(max_length=255, verbose_name="Awwards Winning"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Us",
                "verbose_name_plural": "About Us",
            },
        ),
    ]
