# Generated by Django 5.2.1 on 2025-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelGuides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelguide',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
