# Generated by Django 5.2.1 on 2025-06-23 12:58

import travelGuides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelGuides', '0002_travelguide_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('user_image', models.FileField(blank=True, null=True, upload_to=travelGuides.models.testimonial_user_image_upload_path)),
                ('rating', models.PositiveIntegerField(default=1)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
