# Generated by Django 4.2.24 on 2025-11-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="User Name")),
                ("email", models.CharField(max_length=200, verbose_name="User Email")),
                (
                    "phone_no",
                    models.CharField(max_length=15, verbose_name="User phone no"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Subject")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contact Us",
                "verbose_name_plural": "Contact Us",
                "ordering": ["-created_at"],
            },
        ),
    ]
