# Generated by Django 5.2.3 on 2025-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
