# Generated by Django 5.2.1 on 2025-06-24 11:54

import autoslug.fields
import django.db.models.deletion
import jobs.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to=jobs.models.jobs_upload_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Jobs List',
            },
        ),
        migrations.CreateModel(
            name='ReceiveJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to=jobs.models.job_applications_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobs')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
            },
        ),
    ]
