# Generated by Django 5.2.3 on 2025-08-05 05:42

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Trave_Packages_Management', '0006_quotationinfo'),
        ('setting', '0013_ourgallery_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('Quotation', 'Quotation'), ('Package', 'Package')], default='Quotation', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=20)),
                ('departure_date', models.DateField()),
                ('destination', models.CharField(max_length=100)),
                ('duration', models.IntegerField(help_text='Duration in days')),
                ('no_person', models.IntegerField(help_text='No Person for the enquiry include chldren')),
                ('hotel_type', models.CharField(choices=[('5_star', '5 Star'), ('4_star', '4 Star'), ('3_star', '3 Star'), ('2_star', '2 Star'), ('1_star', '1 Star')], default='3_star', max_length=10)),
                ('tourdetails', tinymce.models.HTMLField(help_text='Enter please send your tour details')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('sub_total_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('other_charges_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('other_charges_info', models.TextField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('failed', 'failed'), ('pending', 'pending'), ('success', 'success')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_categories', to='setting.categories')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_country', to='setting.countries')),
                ('quotationInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_quotationInfo', to='Trave_Packages_Management.quotationinfo')),
                ('travelPackage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_travelPackage', to='Trave_Packages_Management.travelpackage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
