# Generated by Django 5.2.1 on 2025-06-24 05:38

import autoslug.fields
import tinymce.models
import travelGuides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelGuides', '0004_alter_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to=travelGuides.models.our_services_image_upload_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Our Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
