# Generated by Django 4.2.24 on 2025-12-09 08:16

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cms",
            options={
                "verbose_name": "Content List",
                "verbose_name_plural": "Content List",
            },
        ),
        migrations.AlterField(
            model_name="cms",
            name="image",
            field=models.FileField(
                blank=True,
                default=None,
                max_length=250,
                null=True,
                upload_to=cms.models.cms_image_upload_path,
            ),
        ),
    ]
