# Generated by Django 5.2.1 on 2025-06-05 07:40

import autoslug.fields
import blog.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('image', models.FileField(blank=True, null=True, upload_to=blog.models.user_image_upload_path)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog List',
            },
        ),
    ]
